'use client';
import {useState,useEffect} from 'react';
import {Activity,ArrowUpRight,ArrowRight,Wallet,Download,Clock3,ShieldCheck,Layers3,HelpCircle,SlidersHorizontal,ExternalLink,Search,Bell,Plus,X} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import ledger from './ledger.json';
const ps=[{id:1,nft:'1543159',symbol:'PONS',active:false,capital:11239.106507,value:13857.16804,cost:11.381925,pnl:2606.679608,roi:23.169479,il:3696.59,date:'09/05',fees:'429.014746 PONS + 287.144782 USDG'},{id:2,nft:'1989237',symbol:'SHROOM',active:false,capital:4032.840756,value:2687.509363,cost:1.295806,pnl:-1346.627199,roi:-33.380804,il:494.95,date:'09/06',fees:'3,661.072748 SHROOM + 40.089311 USDG'},{id:3,nft:'1988906',symbol:'PONS',active:true,capital:9801.946812,value:9129.704868,cost:1.357075,pnl:-673.599019,roi:-6.871143,il:null,date:'09/07 15:26',fees:'69.230445 PONS + 53.669261 USDG'}];
const names=['','池一','池二','池三'];
const fmt=(v:number)=>v.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const sign=(v:number)=>(v>=0?'+':'−')+'$'+fmt(Math.abs(v));
function Token({symbol}:{symbol:string}){return <span className={'token '+(symbol==='SHROOM'?'mush':'')}>{symbol==='SHROOM'?'S':'P'}<i>$</i></span>}
function csv(name:string,rows:string[][]){const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(r=>r.map(c=>'"'+c.replaceAll('"','""')+'"').join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
export default function Home(){
 const [tab,setTab]=useState('overview'),[filter,setFilter]=useState('all'),[selected,setSelected]=useState<number|null>(null),[query,setQuery]=useState(''),[lp,setLp]=useState('all');
 const [price,setPrice]=useState(.70519),[cost,setCost]=useState(.16535),[daily,setDaily]=useState(109.2032),[q,setQ]=useState(84.91),[u,setU]=useState(59.92),[explain,setExplain]=useState(false);
 const [hash,setHash]=useState(''),[pending,setPending]=useState<string[]>([]),[notice,setNotice]=useState(''),[time,setTime]=useState('12:00');
 useEffect(()=>{try{setPending(JSON.parse(localStorage.getItem('lp-pending')||'[]'));setTime(localStorage.getItem('lp-time')||'12:00')}catch{}},[]);
 const p=ps.find(p=>p.id===selected),valid=[price,cost,daily].every(x=>Number.isFinite(x)&&x>0)&&[q,u].every(x=>Number.isFinite(x)&&x>=0),inRange=price>=.44863&&price<=1.79387;
 const liq=7934.2/(1/Math.sqrt(.70519)-1/Math.sqrt(1.79387)),px=Math.max(.44863,Math.min(1.79387,price)),pq=liq*(1/Math.sqrt(px)-1/Math.sqrt(1.79387)),pu=liq*(Math.sqrt(px)-Math.sqrt(.44863)),value=pq*price+pu,weight=pq*price/value,available=Math.min(weight>0?q*price/weight:Infinity,weight<1?u/(1-weight):Infinity),threshold=Math.sqrt(2*cost*value);
 const rows=ledger.filter(r=>(lp==='all'||r.pool===Number(lp))&&`${r.hash} ${r.action} ${r.symbol}`.toLowerCase().includes(query.toLowerCase()));
 function add(){if(!/^0x[0-9a-fA-F]{64}$/.test(hash)){setNotice('請輸入完整的交易雜湊。');return}if(ledger.some(r=>r.hash.toLowerCase()===hash.toLowerCase())||pending.some(r=>r.toLowerCase()===hash.toLowerCase())){setNotice('交易已存在，不會重複計入。');return}const next=[...pending,hash];setPending(next);localStorage.setItem('lp-pending',JSON.stringify(next));setHash('');setNotice('已存至此瀏覽器，待核對後才計入收益。')}
 return <div className="app-shell"><header className="topbar"><a href="#" className="brand" onClick={e=>{e.preventDefault();setTab('overview')}}><span className="brandmark"><Activity size={22}/></span>LP <strong>觀測台</strong><small>個人賬本</small></a><div className="topright"><span className="network"><i/> Robinhood Chain</span><span className="wallet"><Wallet size={15}/> 0x0df5…11ec</span></div></header><main>
 <div className="page-heading"><div><div className="eyebrow">PORTFOLIO / 01</div><h1>每一筆投入，都有跡可循。</h1><p>三個 LP 倉位的收益、成本與下一步。</p></div><Button variant="outline" onClick={()=>csv('LP結算-20260907.csv',[['池子','投入','價值','費用','淨盈虧','收益率'],...ps.map(p=>[names[p.id],String(p.capital),String(p.value),String(p.cost),String(p.pnl),String(p.roi)])])}><Download size={16}/> 匯出結算</Button></div>
 <div className="snapshot"><Clock3 size={16}/><span><strong>歷史結算快照</strong> · 2026/09/07 15:26（北京時間）</span><span className="snapshot-right">每小時更新 · 尚未接通</span></div>
 <Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList variant="line" className="main-tabs"><TabsTrigger value="overview">收益總覽</TabsTrigger><TabsTrigger value="reinvest">復投評估</TabsTrigger><TabsTrigger value="ledger">交易賬本</TabsTrigger><TabsTrigger value="settings">資料與設定</TabsTrigger></TabsList>
 <TabsContent value="overview"><section className="metrics"><article className="metric hero-metric"><div className="metric-label">整體淨盈虧 <span>含持倉浮動</span></div><strong>+$586<span>.45</span></strong><div><b className="gain-pill"><ArrowUpRight size={15}/> 5.17%</b><span className="metric-note">已扣已知成本</span></div></article>{[{label:'策略資產估值',whole:'11,925',part:'73',note:'LP、餘幣及策略閒置資金'},{label:'外部本金',whole:'11,334',part:'61',note:'池間轉入、復投不重複累加'},{label:'已知總成本',whole:'14',part:'03',note:'Gas $4.67 · 前置成本 $9.37'}].map(x=><article key={x.label} className="metric"><div className="metric-label">{x.label}<Layers3 size={16}/></div><strong>${x.whole}<span>.{x.part}</span></strong><p>{x.note}</p></article>)}</section>
 <div className="overview-grid"><section className="panel contribution"><div className="panel-top"><div><h2>收益來自哪裡</h2><p>各池淨盈虧貢獻 · USDG</p></div><span className="small-label">已扣成本</span></div><div className="bars">{ps.map(p=><button className="bar-row" key={p.id} onClick={()=>setSelected(p.id)}><span>{names[p.id]} <small>{p.symbol}</small></span><div className="bar-track"><div className={p.pnl>0?'positive-bar':'negative-bar'} style={{width:Math.abs(p.pnl)/2606.68*100+'%'}}/></div><b className={p.pnl>0?'positive':'negative'}>{sign(p.pnl)}</b></button>)}</div><div className="contribution-footer"><span>已退出兩池結算 <b className="positive">+$1,260.05</b></span><span>池三浮動 <b className="negative">−$673.60</b></span></div><p className="footnote">已退出結果含 PONS 結轉估值，並非全部兌現為穩定幣。</p></section><section className="panel apr-panel"><div className="panel-top"><div><h2>池子 APR</h2><p>PONS / USDG · 池三</p></div><span className="badge amber">待接入</span></div><div className="empty-chart"><div className="chart-grid"/><Activity size={28}/><strong>等待第一筆 APR 觀測</strong><p>接通 Uniswap 同口徑來源後，<br/>每小時採樣，形成日 K 線。</p></div><div className="apr-footer">不以個人收益率替代池子 APR <ArrowRight size={14}/></div></section></div>
 <section className="panel position-panel"><div className="panel-top"><div><h2>我的倉位 <span className="count">3</span></h2><p>只納入你確認與 LP 相關的交易</p></div><Tabs value={filter} onValueChange={v=>setFilter(String(v))}><TabsList><TabsTrigger value="all">全部</TabsTrigger><TabsTrigger value="active">運行中</TabsTrigger><TabsTrigger value="closed">已關閉</TabsTrigger></TabsList></Tabs></div><Table><TableHeader><TableRow><TableHead>倉位</TableHead><TableHead>狀態</TableHead><TableHead className="numeric">投入成本</TableHead><TableHead className="numeric">回款 / 資產價值</TableHead><TableHead className="numeric">淨盈虧</TableHead><TableHead className="numeric">收益率</TableHead><TableHead/></TableRow></TableHeader><TableBody>{ps.filter(p=>filter==='all'||(filter==='active'?p.active:!p.active)).map(p=><TableRow key={p.id}><TableCell><button className="position-title" onClick={()=>setSelected(p.id)}><Token symbol={p.symbol}/><span><strong>{p.symbol} / USDG</strong><small>{names[p.id]} · #{p.nft}</small></span></button></TableCell><TableCell><span className={'badge '+(p.active?'live':'closed')}>{p.active?'運行中':'已關閉'}</span></TableCell><TableCell className="numeric">${fmt(p.capital)}</TableCell><TableCell className="numeric">${fmt(p.value)}</TableCell><TableCell className={'numeric '+(p.pnl>0?'positive':'negative')}>{sign(p.pnl)}</TableCell><TableCell className={'numeric '+(p.roi>0?'positive':'negative')}>{p.roi>0?'+':''}{p.roi.toFixed(2)}%</TableCell><TableCell><Button variant="ghost" size="icon" aria-label={'查看'+names[p.id]} onClick={()=>setSelected(p.id)}><ArrowUpRight size={17}/></Button></TableCell></TableRow>)}</TableBody></Table><div className="table-note"><ShieldCheck size={15}/> 無常損失不再次扣除。各池本金與收益率不直接相加。</div></section><div className="bottom-callout"><Bell size={20}/><div><strong>池三的下一次復投，先看配幣和成本。</strong><p>使用已確認截圖試算；尚未啟用自動提醒。</p></div><Button variant="outline" onClick={()=>setTab('reinvest')}>查看參考門檻 <ArrowRight size={15}/></Button></div></TabsContent>
 <TabsContent value="reinvest"><div className="section-intro"><h2>把等待與成本，一起算進去。</h2><p>池三 · 9月8日使用者截圖參數，不影響歷史結算</p></div><div className="assessment-grid"><section className="panel assessment"><span className="badge amber">條件試算 · 非即時建議</span><h2>當可配對復投的費用達到</h2><div className="threshold">{valid&&inRange?'$'+fmt(threshold):'—'}<span>再考慮操作</span></div><p>每天檢查一次，不必每天一定復投。</p><div className="assessment-state">{!valid?'請填入有效參數。':!inRange?'價格已出區間，暫停常規復投評估。':available>=threshold?'輸入的配對餘額已達基礎模型參考規模。':'配對餘額尚未達基礎模型參考規模。'}</div><dl className="stats"><div><dt>可直接配對復投</dt><dd>{valid?'$'+fmt(available):'—'}</dd></div><div><dt>總費用餘額</dt><dd>{valid?'$'+fmt(q*price+u):'—'}</dd></div><div><dt>所需 PONS / USDG 比例</dt><dd>{valid?(weight*100).toFixed(1)+'% / '+((1-weight)*100).toFixed(1)+'%':'—'}</dd></div><div><dt>未配對的 USDG</dt><dd>{valid?fmt(Math.max(0,u-available*(1-weight))):'—'}</dd></div></dl><Button variant="outline" onClick={()=>setExplain(!explain)}><HelpCircle size={16}/>{explain?'收起計算依據':'了解計算依據'}</Button>{explain&&<div className="formula"><b>H ≈ √(2 × C × P)</b><p>C為尚未發生的操作成本，P為LP價值。基礎模型假設價格與收益率穩定、新費用可配對復投、不需換幣。</p><p>此為可復投金額門檻，不是全部手續費總值。持倉波動、配比限制需另行評估，不保證總收益最優。</p><p>理想累積時間約 {valid?(24*threshold/daily).toFixed(1):'—'} 小時；已有餘額時不是需再等待的時間。</p></div>}</section><section className="panel params"><div className="panel-top"><div><h2>評估參數</h2><p>只用於試算，不會執行交易</p></div><SlidersHorizontal size={20}/></div>{[{label:'PONS 價格 · USDG',v:price,s:setPrice,step:.00001},{label:'後續加倉成本 · USDG（可修改）',v:cost,s:setCost,step:.01},{label:'日新增費用估值 · USDG',v:daily,s:setDaily,step:1},{label:'已領取未復投 · PONS',v:q,s:setQ,step:.01},{label:'已領取未復投 · USDG',v:u,s:setU,step:.01}].map(x=><label className="field" key={x.label}>{x.label}<Input type="number" min="0" step={x.step} value={x.v} onChange={e=>x.s(Number(e.target.value))}/></label>)}<div className="subtle-box">基準截圖：7,934.20 PONS + 3,035.74 USDG<br/>價格區間：0.44863 — 1.79387<br/>已領取費用合併兩次 collect；未領取費用尚未知。改動價格時按集中流動性公式估算配比；加倉成本為歷史估算，請以最新報價修正。</div><Button variant="ghost" onClick={()=>{setPrice(.70519);setCost(.16535);setDaily(109.2032);setQ(84.91);setU(59.92)}}>還原截圖參數</Button></section></div></TabsContent>
 <TabsContent value="ledger"><div className="section-intro"><h2>已確認的每一筆。</h2><p>不自動納入錢包其他交易。新交易待核對後才影響收益。</p></div><section className="panel"><div className="panel-top"><div className="search"><Search size={17}/><Input aria-label="搜尋交易" placeholder="操作、代幣或雜湊" value={query} onChange={e=>setQuery(e.target.value)}/></div><Tabs value={lp} onValueChange={v=>setLp(String(v))}><TabsList><TabsTrigger value="all">全部</TabsTrigger>{ps.map(p=><TabsTrigger key={p.id} value={String(p.id)}>{names[p.id]}</TabsTrigger>)}</TabsList></Tabs><Button variant="outline" onClick={()=>csv('LP交易.csv',[['池子','時間','操作','USDG','代幣','數量','交易'],...rows.map(r=>[names[r.pool],r.time,r.action,String(r.usd),r.symbol,String(r.token),r.hash])])}><Download size={15}/> CSV</Button></div><Table><TableHeader><TableRow><TableHead>時間（北京）</TableHead><TableHead>倉位</TableHead><TableHead>操作</TableHead><TableHead className="numeric">USDG收支</TableHead><TableHead className="numeric">代幣收支</TableHead><TableHead>鏈上記錄</TableHead></TableRow></TableHeader><TableBody>{rows.map(r=><TableRow key={r.hash}><TableCell className="muted">{r.time}</TableCell><TableCell>{names[r.pool]}</TableCell><TableCell>{r.action}</TableCell><TableCell className="numeric">{r.usd>0?'+':''}{fmt(r.usd)}</TableCell><TableCell className="numeric">{r.token>0?'+':''}{fmt(r.token)} <small>{r.symbol}</small></TableCell><TableCell><a className="txlink" href={'https://robinhoodchain.blockscout.com/tx/'+r.hash} target="_blank" rel="noreferrer">{r.hash.slice(0,8)}… <ExternalLink size={12}/></a></TableCell></TableRow>)}</TableBody></Table>{!rows.length&&<p className="empty-text">沒有符合條件的已確認交易。</p>}</section><section className="panel pending"><h2>補充相關交易</h2><p>僅保存在此瀏覽器的待核對清單，尚未寫入結算。</p><div className="add-row"><Input aria-label="交易雜湊" placeholder="0x… 完整交易雜湊" value={hash} onChange={e=>setHash(e.target.value)}/><Button onClick={add}><Plus size={16}/> 加入待核對</Button></div>{notice&&<p role="status">{notice}</p>}{pending.map(h=><div className="pending-row" key={h}><span>{h}</span><span className="badge amber">待核對</span><Button variant="ghost" size="icon" aria-label="移除項目" onClick={()=>{const next=pending.filter(x=>x!==h);setPending(next);localStorage.setItem('lp-pending',JSON.stringify(next))}}><X size={15}/></Button></div>)}</section></TabsContent>
 <TabsContent value="settings"><div className="section-intro"><h2>可信的數據，明確的邊界。</h2><p>只讀評估，不需要簽名、不處理錢包其他資產。</p></div><div className="overview-grid"><section className="panel"><h2>資料來源</h2>{[['歷史賬本','已導入','三池已確認回執與歷史結算'],['每小時更新','待接入','需持續運行的後端與可靠節點'],['Uniswap 池子 APR','待核實','需要顯示 APR 的池子頁面連結'],['每日門檻提醒','未啟用','目前只提供手動參數試算']].map((x,i)=><div className="source-row" key={i}><div><strong>{x[0]}</strong><p>{x[2]}</p></div><span className={'badge '+(i===0?'live':'amber')}>{x[1]}</span></div>)}</section><section className="panel params"><h2>評估偏好</h2><label className="field">每日評估時間 · 北京時間<Input type="time" value={time} onChange={e=>{setTime(e.target.value);localStorage.setItem('lp-time',e.target.value)}}/></label><div className="subtle-box">偏好只存於此瀏覽器。排程服務尚未啟用，關閉頁面後不會採集或發送提醒。</div><h3>賬本範圍</h3><p>池一、池二已關閉，池三運行中。其他交易只有你確認後才納入。</p><h3>整體收益口徑</h3><p>含費成本 $11,339.28。前置成本已含於原始USDT支出，僅額外加入Gas。收益率不是年化。</p></section></div></TabsContent>
 </Tabs><footer><span><ShieldCheck size={14}/> 只讀評估 · 已確認 LP 交易範圍</span><span>USDG / USDT 按 $1 核算 · 非即時行情</span></footer></main>
 <Sheet open={selected!==null} onOpenChange={open=>{if(!open)setSelected(null)}}><SheetContent className="detail-sheet">{p&&<><SheetHeader><SheetTitle><span className="detail-title"><Token symbol={p.symbol}/>{p.symbol} / USDG</span></SheetTitle><SheetDescription>{names[p.id]} · #{p.nft} · 2026/{p.date}</SheetDescription></SheetHeader><div className="detail-body"><div className="detail-pnl"><span>{p.active?'扣 Gas 後浮動盈虧':'扣成本後結算盈虧'}</span><strong className={p.pnl>0?'positive':'negative'}>{sign(p.pnl)}</strong><span>{p.roi.toFixed(2)}% · 歷史結算</span></div><dl className="stats">{[['投入成本','$'+fmt(p.capital)],['回款 / 策略資產','$'+fmt(p.value)],['已知費用','$'+fmt(p.cost)],['無常損失',p.il===null?'待核算':'$'+fmt(p.il)]].map(x=><div key={x[0]}><dt>{x[0]}</dt><dd>{x[1]}</dd></div>)}</dl>{p.active&&<><h3>價格區間</h3><div className="range-track"><span style={{left:'23.68%'}}/></div><div className="range-labels"><span>0.44863</span><b>0.76721</b><span>1.79387</span></div><p>LP內：7,056.27 PONS + 3,681.50 USDG</p><p>池外餘幣：19.10 PONS + 19.89 USDG</p></>}<h3>已明確提取的費用</h3><p>{p.fees}</p><div className="subtle-box">費用已包含在收益中，不額外加一次。無常損失也不重複扣款。{p.id===1?'池一包含轉入池三的PONS結轉估值。':''}</div><Button variant="outline" onClick={()=>{setLp(String(p.id));setTab('ledger');setSelected(null)}}>查看此倉位流水 <ArrowRight size={15}/></Button></div></>}</SheetContent></Sheet></div>
}

