'use client';
import {useState,useEffect} from 'react';
import data from './pool-market.json';
import {Button} from '@/components/ui/button';
type Sample={sampledAt:string;[key:string]:unknown};
const format=(n:unknown,suffix='')=>typeof n==='number'&&Number.isFinite(n)?n.toLocaleString('en-US',{maximumFractionDigits:2})+suffix:'暫缺';
function Chart({rows,field,label,bars=false}:{rows:Sample[];field:string;label:string;bars?:boolean}){
 const values=rows.map((r,i)=>({i,v:r[field],time:r.sampledAt})).filter(x=>typeof x.v==='number'&&Number.isFinite(x.v)) as {i:number;v:number;time:string}[];
 if(!values.length)return <p className="subtle-box">{label}：尚無有效樣本，資料缺失不填零。</p>;
 const min=bars?0:Math.min(...values.map(x=>x.v)),max=Math.max(...values.map(x=>x.v)),range=Math.max(max-min,max*.01,1),x=(i:number)=>45+i*490/Math.max(rows.length-1,1),y=(v:number)=>140-(v-min)/range*110;
 return <div><h3>{label}</h3><svg viewBox="0 0 560 185" role="img" aria-label={label+'歷史採樣'} style={{width:'100%'}}><text x="5" y="20" fontSize="12">{format(max)}</text><text x="5" y="150" fontSize="12">{format(min)}</text>{values.map((p,i)=>{const prev=values[i-1];return <g key={p.time}><title>{new Date(p.time).toLocaleString('zh-TW')}：{format(p.v)}</title>{!bars&&prev&&prev.i===p.i-1&&Date.parse(p.time)-Date.parse(prev.time)<=9*3600000&&<line x1={x(prev.i)} y1={y(prev.v)} x2={x(p.i)} y2={y(p.v)} stroke="#238064" strokeWidth="2"/>}{bars?<rect x={x(p.i)-5} y={y(p.v)} width="10" height={140-y(p.v)} fill="#238064"/>:<circle cx={x(p.i)} cy={y(p.v)} r="4" fill="#238064"/>}</g>})}<text x="45" y="175" fontSize="12">{new Date(rows[0].sampledAt).toLocaleDateString('zh-TW')}</text><text x="420" y="175" fontSize="12">{new Date(rows.at(-1)!.sampledAt).toLocaleDateString('zh-TW')}</text></svg><p className="footnote">{values.length} 個有效樣本；只有一個樣本時顯示單點。</p></div>
}
export default function PoolMarket(){
 const [days,setDays]=useState(7),[now,setNow]=useState(Date.parse(data.attemptedAt));useEffect(()=>{setNow(Date.now())},[]);
 const s=data.latest as Sample|null,rows=(data.history as Sample[]).filter(r=>!days||Date.parse(r.sampledAt)>=now-days*86400000),stale=!s||now-Date.parse(s.sampledAt)>10*3600000;
 return <section className="panel" style={{margin:'24px 0'}}><div className="panel-top"><div><h2>PONS / USDG · 整池監控</h2><p>Robinhood Chain · V4 · 每8小時採樣</p></div><span className="badge amber">{stale?'資料過期':String(s?.status||'暫缺')}</span></div><p>最後採集：{s?new Date(s.sampledAt).toLocaleString('zh-TW',{timeZone:'Asia/Shanghai'}):'—'}（北京時間）</p><div className="overview-grid">{[['官方接口 TVL','officialTvl','$'],['代幣數量估算 TVL','reserveTvl','$'],['PONS 美元價格','ponsPrice','$'],['USDG 美元價格','usdgPrice','$'],['PONS 數量','ponsReserves',''],['USDG 數量','usdgReserves',''],['24H 成交量','volume24h','$'],['24H LP費用估算','fees24h','$'],['費用 APR 估算','apr','%'],['官方 Total APR','officialApr','%'],['理論 APY（日複投）','apy','%']].map(([label,key,unit])=><div key={key}><p>{label}</p><strong>{unit==='$'&&typeof s?.[key]==='number'?'$':''}{format(s?.[key],unit==='%'?'%':'')}</strong></div>)}</div><p>鏈上 LP 費率：{typeof s?.feeTier==='number'?format(s.feeTier*100,'%'):'暫缺'} · 原始接口費率值：{format(s?.apiFeePips)}（不可直接當作LP費率）</p>{typeof s?.tvlDifference==='number'&&Math.abs(s.tvlDifference)>2&&<p className="subtle-box">兩種 TVL 口徑相差 {format(s.tvlDifference,'%')}；價格時間與數量統計可能不同，需核對。暫不視為等價資料。</p>}<p className="footnote">數量來自官方前端 GraphQL 的 tokenSupply，尚未以 pool_info 儲備核對。pool_info 的 API Key 尚未配置。成交量返回缺失時，APR/APY 保持暫缺。</p><div style={{display:'flex',gap:8,margin:'20px 0'}}>{[[1,'24小時'],[7,'7天'],[30,'30天'],[0,'全部']].map(([d,l])=><Button key={d} variant={days===d?'default':'outline'} onClick={()=>setDays(Number(d))}>{l}</Button>)}</div><div className="overview-grid"><Chart rows={rows} field="officialTvl" label="官方接口 TVL · USD"/><Chart rows={rows} field="apr" label="費用 APR · %"/><Chart rows={rows} field="apy" label="理論 APY · %"/><Chart rows={rows} field="fees24h" label="滾動24H LP費用 · USD" bars/></div><details><summary>資料來源與計算方法</summary><p>官方接口值：TVL、代幣數量、美元價格、24H成交量。TVL估算＝兩種數量各乘美元價格後相加。費用估算＝24H成交量×鏈上LP費率；動態費率不套固定公式。</p><p>APR百分數＝費用÷TVL×365×100。APY百分數＝[(1＋APR百分數÷100÷365)^365−1]×100。APY假設全年收益率不變、每天複投，不扣Gas或價格損失；不是可保證的收益。</p><p>官方 Total APR 尚未取得，可能含獎勵，不以估算值冒充。歷史從成功採集起累積，24H費用是重疊滾動窗口，不可把各快照加總成收入。排程依賴本機Codex運行。</p><a href="https://app.uniswap.org/explore/pools/robinhood/0x4be9657ec9002e528f4f17a5c43edc525a07f888f7b180c2afbf75e096c4f38a" target="_blank" rel="noreferrer">查看 Uniswap 池子</a></details></section>
}
