'use client';
import {useState} from 'react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid,Legend} from 'recharts';
import data from './data.json';
import './style.css';
type Point={date:string|null;group:string|null;value:number|null};
type Source={queryId:number;executedAt?:string;fetchedAt?:string;error?:string|null;points:Point[]};
const sources=data.sources as Record<string,Source>;
const labels:Record<string,string>={chain:'Robinhood 日成交量',pons:'Pons 日成交量',share:'Pons 已计价份额',revenue:'Pons 日协议收入',launches:'24H Token 发行量',burn:'累计 PONS 销毁',platforms:'三平台成交量对比'};
const colors=['#173b35','#2689de','#36b4af'];
const sourceKey=(k:string)=>k==='share'?'launchpads':k;
const number=(v:number|null|undefined,k='')=>v==null?'—':(k==='share'?v.toFixed(2)+'%':(k==='launches'||k==='burn'?'':'$')+v.toLocaleString('en-US',{notation:'compact',maximumFractionDigits:2})+(k==='burn'?' PONS':''));
const day=(s:string)=>s.slice(0,10);
function series(k:string){const s=sources[sourceKey(k)];const buckets:Record<string,Point[]>={};for(const p of s.points){if(p.date)(buckets[day(p.date)]||=[]).push(p)}return Object.entries(buckets).sort(([a],[b])=>a.localeCompare(b)).map(([date,rows])=>{const total=rows.every(r=>r.value===null)?null:rows.filter(r=>r.value!==null).reduce((n,r)=>n+r.value!,0);const pons=rows.find(r=>r.group==='ponsfamily.com')?.value;return {date,value:k==='share'?(total&&pons!=null?pons/total*100:null):k==='burn'?rows.at(-1)?.value:total}})}
const time=(s?:string)=>s?new Date(s).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'未知';
function status(k:string){const s=sources[sourceKey(k)];return s.error?'采集失败 · 保留上次数据':!s.executedAt?'暂无数据':Date.now()-Date.parse(s.executedAt)>36*3600000?'源结果超过36小时':'Dune 数据'}
function Chart({rows,keys=['value'],percent=false,unit=''}:{rows:any[];keys?:string[];percent?:boolean;unit?:string}){return <div className="eco-chart">{rows.length?<ResponsiveContainer width="100%" height="100%"><LineChart data={rows} margin={{left:8,right:18,top:12,bottom:4}}><CartesianGrid vertical={false} stroke="#e8efed"/><XAxis dataKey="date" tickFormatter={v=>v.slice(5)} minTickGap={40}/><YAxis width={74} tickFormatter={v=>percent?v+'%':number(v,unit)}/><Tooltip formatter={(v:any)=>percent?Number(v).toFixed(2)+'%':number(Number(v),unit)}/>{keys.length>1&&<Legend/>}{keys.map((k,i)=><Line key={k} name={k==='value'?'数值':k} dataKey={k} stroke={colors[i%3]} dot={rows.length<3} strokeWidth={2} connectNulls={false} isAnimationActive={false}/>)}</LineChart></ResponsiveContainer>:<p>此区间暂无完整数据</p>}</div>}
export default function Ecosystem(){const [metric,setMetric]=useState('pons'),[range,setRange]=useState(30);const base=series(metric);const newest=base.at(-1)?.date;const cutoff=newest?Date.parse(newest)-(range-1)*86400000:0;const shown=base.filter(p=>Date.parse(p.date)>=cutoff);const pads=series('share').filter(p=>Date.parse(p.date)>=cutoff).map(p=>{const rows=sources.launchpads.points.filter(r=>r.date&&day(r.date)===p.date);const total=rows.every(r=>r.value===null)?null:rows.filter(r=>r.value!==null).reduce((n,r)=>n+r.value!,0);const a=rows.find(r=>r.group==='ponsfamily.com')?.value,b=rows.find(r=>r.group==='long.xyz')?.value;return {date:p.date,Pons:total&&a!=null?a/total*100:null,'long.xyz':total&&b!=null?b/total*100:null,'其余已识别平台':total&&a!=null&&b!=null?(total-a-b)/total*100:null}});const platformDates=[...new Set(sources.platforms.points.map(p=>p.date).filter(Boolean))].sort();const pd=platformDates.filter(d=>sources.platforms.points.filter(p=>p.date===d).length===3&&sources.platforms.points.filter(p=>p.date===d).every(p=>p.value!=null)).at(-1);const platforms=sources.platforms.points.filter(p=>p.date===pd);const launches=[...sources.launches.points].sort((a,b)=>(b.value||0)-(a.value||0));
return <div><header className="eco-nav"><a href="/">LP 观测台</a><nav><a href="/">收益总览</a><a href="/ecosystem" aria-current="page">生态监控</a><a href="/">返回个人账本</a></nav></header><main className="eco"><h1>Robinhood / Pons 生态监控</h1><p>全链需求 · 平台竞争 · 协议收入</p><div className="eco-cards">{Object.keys(labels).map(k=>{const src=sources[sourceKey(k)];const latest=k==='launches'?null:series(k).at(-1);const value=k==='launches'?src.points.reduce((n,p)=>n+(p.value||0),0):latest?.value;return <button key={k} className={'eco-card '+(metric===k?'selected':'')} onClick={()=>{if(k==='launches')document.getElementById('issuance')?.scrollIntoView({behavior:'smooth'});else if(k==='platforms')document.getElementById('platforms')?.scrollIntoView({behavior:'smooth'});else setMetric(k)}}><span>{labels[k]}</span><strong>{k==='platforms'?'Pons / pumpfun / stonkfun':number(value,k)}</strong><small>{k==='launches'?'查询执行时点向前24小时':k==='platforms'?'跨链平台对比 · 非全市场份额':'统计至 '+(latest?.date||'—')+' UTC'}</small><small>{status(k)}</small></button>})}</div>
<section className="panel"><div className="eco-controls"><h2>历史趋势</h2><select aria-label="选择趋势指标" value={metric} onChange={e=>setMetric(e.target.value)}>{Object.entries(labels).filter(([k])=>!['launches','platforms'].includes(k)).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select><div>{[7,30,90,36500].map(n=><button aria-pressed={range===n} key={n} onClick={()=>setRange(n)}>{n===36500?'全部':n+'D'}</button>)}</div></div><Chart rows={shown} unit={metric} percent={metric==='share'}/><p className="footnote">时间范围截至本指标最新统计日；日级数据为 UTC 自然日，不是滚动24小时。{metric==='burn'?'累计转入零地址及 dead 地址，不等同于 totalSupply 减少。':''} {metric==='pons'?'独立 Pons 查询的过滤与估价口径不同于份额查询。':''}</p><p className="footnote">源查询完成：{time(sources[sourceKey(metric)].executedAt)}（北京时间）</p></section>
<div className="eco-two"><section className="panel"><h2>Launchpad 竞争份额</h2><Chart rows={pads} keys={['Pons','long.xyz','其余已识别平台']} percent/><p className="footnote">Robinhood 已识别平台，同日同源成交量占比；排除未归属 other。仅统计已计价成交量；金额缺失的平台记录不计入分母，份额可能偏高。</p></section><section className="panel" id="platforms"><h2>三平台成交量对比</h2><p>最近共同完整日：{pd||'—'} UTC</p>{platforms.map((p,i)=><div className="eco-bar" key={p.group}><span>{p.group}</span><div><i style={{width:((p.value||0)/Math.max(...platforms.map(x=>x.value||0),1)*100)+'%',background:colors[i%3]}}/></div><b>{number(p.value)}</b></div>)}<p>仅比较 Pons、pumpfun 和 stonkfun，涉及不同链；不代表全市场份额。</p><small>{status('platforms')}</small></section></div>
<section className="panel" id="issuance"><h2>最近24小时发行排行</h2><p>按源查询统计新增 Token；截至 {time(sources.launches.executedAt)}（北京时间）。近期首次铸造日志口径，尚未独立核验全历史首次发行。</p><div className="eco-table"><table><thead><tr><th>排名</th><th>Launchpad</th><th>发行数量</th></tr></thead><tbody>{launches.map((p,i)=><tr key={p.group}><td>{i+1}</td><td>{p.group}</td><td>{p.value?.toLocaleString()??'—'}</td></tr>)}</tbody></table></div><p className="footnote">滚动快照不能累加为7日发行量。{status('launches')}</p></section>
<details className="panel"><summary>数据来源与统计口径</summary><p>全链及份额合计仅包含已计价成交量；缺失金额不视为零，可能低估总量或影响份额。</p><p>每8小时尝试获取 Dune 最近执行结果；获取时间不代表源数据更新。各查询独立保留最近成功结果。协议收入来自查询作者维护的数据集，创作者收入不并入协议收入。</p>{Object.entries(sources).map(([k,s])=><p key={k}><a href={'https://dune.com/queries/'+s.queryId} target="_blank" rel="noreferrer">Dune {s.queryId}</a> · {k} · 源执行 {time(s.executedAt)} · 采集 {time(s.fetchedAt)} · {status(k)}{s.error?' · '+s.error:''}</p>)}</details></main></div>}
